### PR TITLE
add entry for rayclient to allow all connections

### PR DESCRIPTION
**Pull request by KPostOffice**
# Issue link

# What changes have been made

# Verification steps

## Checks
- [ ] I've made sure the tests are passing. 
- Testing Strategy
   - [ ] Unit tests
   - [ ] Manual tests
   - [ ] Testing is not required for this change

### CODE REVIEW

**Review by Bobbins228 — COMMENTED** [review]
/lgtm

**Review by ChristianZaccaria — COMMENTED** [review]
/lgtm - Tested - I could successfully connect to the RayClient.

**Comment by astefanutti** [comment]
Closing as superseded by #539.

**Pull request closed without merging**
