### PR TITLE
Disable MCAD by default

### PR DESCRIPTION
**Pull request by anishasthana**
https://issues.redhat.com/browse/RHOAIENG-5129

### CODE REVIEW

**Comment by dgrove-oss** [comment]
You probably know this, but #491 also accomplishes this.  You'll have the same SDK e2e testing issues with this PR that are blocking #491  (and will need to make similar adjustments in the PR to the e2e tests for this repository to get them to work without AppWrappers).

**Comment by anishasthana** [comment]
Heya @dgrove-oss, yep! Just from a risk reduction perspective we need to keep minimal code changes due to some of the other large things that are in motion.

**Comment by jbusche** [comment]
Hi @anishasthana @tedhtchang I tried testing on my OC cluster - glad to re-test/try again tomorrow with extra instructions, but here's what I did so far.
1. OC 4.14.17 with kustomize, podman, etc.
2. Installed ODH 2.10.0 (It won't take startingCSV: opendatahub-operator.v2.4.0 anymore which is annoying)
3. Now I need dsci manually - I applied one, then [dsc ](https://github.ibm.com/ray-project/ray/wiki/Quick-Start-Guide-for-CodeFlare-Stack#step-3-deploy-the-datasciencecluster-with)with CodeFlare Component Removed.  
- I'm having trouble with model-mesh and kserve...  I tried a few things but throwing up my hands for now on that.

4.  So, ok let's see if I can build the image and install it
4.1  clone this PR
git clone --single-branch --branch add_mcad_config_flag https://github.com/anishasthana/codeflare-operator.git
cd codeflare-operator
4.2 See if I can install or build an image
make install
make deploy
make image-build
4.3 tag and push to quay
podman tag quay.io/project-codeflare/codeflare-operator:v0.0.0-anish quay.io/jbusche/codeflare-operator:pr499-anish
podman push quay.io/jbusche/codeflare-operator:pr499-anish
4.4 oc edit deploy codeflare-operator-manager -n openshift-operators
image: quay.io/jbusche/codeflare-operator:pr499-anish
4.5 check that it's running
```
oc get pods -n openshift-operators |grep codeflare
codeflare-operator-manager-fdc56c47b-q947k                 1/1     Running   0              14m
```

I'm leaving it where it is for now... not sure how to resolve the dsc issues or how to make sure KFTO/kueue are up if there's no MCAD.

**Comment by astefanutti** [comment]
Superseded by #500.

**Pull request closed without merging**
