### PR TITLE
Update TLS certificate generation container image

### PR DESCRIPTION
**Pull request by astefanutti**
# Issue link

# What changes have been made

# Verification steps

## Checks
- [ ] I've made sure the tests are passing. 
- Testing Strategy
   - [ ] Unit tests
   - [ ] Manual tests
   - [ ] Testing is not required for this change

### CODE REVIEW

**Comment by Bobbins228** [comment]
/lgtm 
Do we need to update codeflare common dependency? @sutaakar

**Comment by sutaakar** [comment]
@Bobbins228 yes

**Comment by sutaakar** [comment]
rebasing, lets see if it helps

**Review by sutaakar — APPROVED** [review]

**Review by Bobbins228 — APPROVED** [review]

**Pull request merged**
