### PR TITLE
Update instaScale crd and controller

### LINKED ISSUE #52: Update InstaScale Custom Resource to allow users to specific memory and cpu resources

### PR DESCRIPTION
**Pull request by tedhtchang**
Close #52

### CODE REVIEW

**Comment by jbusche** [comment]
I did some testing of this - I did the following on my OC 4.12 cluster:

1.  Fetch the PR
mkdir TED ; cd TED
git clone https://github.com/tedhtchang/codeflare-operator.git
cd codeflare-operator
git checkout update-instascale-crd
oc project openshift-operators

2.  build it: 
make manifests
make install
make run

3. deploy the MCAD cr from the testdata folder
Then, from another terminal
ssh root@9.30.x.x
cd TED/codeflare-operator/
cd controllers/testdata

4.  Test it:
oc apply -f mcad_test_cases/case_1.yaml 
logs look good
oc get pods |grep mcad
mcad-controller-blank-custom-resource-6dbc847b4f-98l9c   1/1     Running   0          31s

oc apply -f instascale_test_cases/case_2.yaml 
logs look good
oc get pods |grep inst
instascale-example2-768d8f49c4-qrmhv                     1/1     Running   0          106s

Then I tried editing the instacale CR to change the cpu and memory values, and the instascale pod correctly re-sized:
oc edit instascale example2
Changed:
```
spec:
  controllerResources:
    limits:
      cpu: "1"
      memory: 1G
    requests:
      cpu: "1"
      memory: 1G
```
to
```
spec:
  controllerResources:
    limits:
      cpu: "3"
      memory: 2G
    requests:
      cpu: "3"
      memory: 2G
```

Then verify it:
```
oc describe pod instascale-example2-65bd8f56d6-fqsx8 |grep mem
      memory:  2G
      memory:     2G
Tolerations:                 node.kubernetes.io/memory-pressure:NoSchedule op=Exists

oc describe pod instascale-example2-65bd8f56d6-fqsx8 |grep cpu
      cpu:     3
      cpu:        3
```

**Review by anishasthana — APPROVED** [review]
Tested it out myself as well.

/lgtm

**Pull request merged**
