### PR TITLE
Upgrade to go 1.21

### PR DESCRIPTION
**Pull request by dgrove-oss**
This pulls out the upgrade to Go 1.21 (required by Kueue and AppWrapper) from #491 into a standalone PR.  Hopefully this makes it easier to handle the downstream build system changes needed for the go update without the additional complexity of simultaneously adding the AppWrapper CRD and controller.  

Obviously, this PR should be held until the downstream repos are ready to make the needed changes, but should be merged before we start working on the remaining pieces of #491.

### CODE REVIEW

**Comment by astefanutti** [comment]
/hold

Making sure everything is setup downstream.

**Review by jiripetrlik — APPROVED** [review]

**Comment by dgrove-oss** [comment]
rebased to resolve conflict in Dockerfile

**Comment by dgrove-oss** [comment]
rebased yet again.

**Pull request merged**
