### PR TITLE
Add client action

### PR DESCRIPTION
**Pull request by anishasthana**
This PR adds github action checks for the following:
1) Generated client
2) Generated manifests
3) Generated code.

This should help ensure that our artifacts are always up to date.

### CODE REVIEW

**Review by astefanutti — COMMENTED** [review]
Do you feel strong about splitting everything into its own workflow. It seems grouping the those checks, together with the openshift-goimports would make their execution faster and spare resources.

**Comment by anishasthana** [comment]
I'll work on consolidating into one action.

**Comment by anishasthana** [comment]
Consolidated.

**Comment by astefanutti** [comment]
/lgtm

We could also add a verification step that check `go mod tidy` induces no diff.

**Review by tedhtchang — COMMENTED** [review]
/LGTM tried [here](https://github.com/tedhtchang/codeflare-operator/actions/runs/5755502568)

**Pull request merged**
