### PR TITLE
Update CodeFlare stack release instructions

### PR DESCRIPTION
**Pull request by anishasthana**

### CODE REVIEW

**Comment by anishasthana** [comment]
@sutaakar  Raising this PR, I was thinking... Maybe we should update the release action to allow users to select _which_ components are going to have releases. This would lessen the burden on users (as opposed to forcing them to manually go to each repo and run the corresponding action)

**Comment by sutaakar** [comment]
@anishasthana It can be done, though it will need some adjustments in workflows.
Just to be sure, the release strategy remains the same, right? By default release all components, occasionally for hotfix release just subset of components.

**Comment by anishasthana** [comment]
>Just to be sure, the release strategy remains the same, right? By default release all components, occasionally for hotfix release just subset of components.

Yep! That's where my head is at. Something like a checkbox would probably suffice

**Review by KPostOffice — COMMENTED** [review]
/lgtm

**Review by KPostOffice — APPROVED** [review]

**Pull request merged**
