### PR TITLE
Run additional bundle validators

### LINKED ISSUE #59: Fix InstaScale CRD Display name
The InstaScale CRD display name is wrong. We should fix the definition in the APIs folder as well as the following manifest updates for the operator as well as the bundle (and CSV).

_Originally posted by @Maxusmusti in https://github.com/project-codeflare/codeflare-operator/pull/41#discussion_r1129640136_

### PR DESCRIPTION
**Pull request by tedhtchang**
- Validate a bundle against the entire suite of validators for Operator Framework as described [here](https://sdk.operatorframework.io/docs/cli/operator-sdk_bundle_validate/#examples).
- Add marker for `make bundle` to re-generate correct InstaScale displayName closes #59
- Improve CSV automation by adding statics annotations (containerImage, repository, mediaType, etc)
- Download operator-sdk binary locally.
- Add validate-bundle job to precommit github workflow.

### CODE REVIEW

**Review by anishasthana — COMMENTED** [review]
/lgtm

Seems reasonable. @tedhtchang is it worth making a github action for this?

**Comment by tedhtchang** [comment]
> /lgtm
> 
> Seems reasonable. @tedhtchang is it worth making a github action for this?

Yes reasonable. `make bundle` would fail with `ERRO[0000] Error: Value : (codeflare-operator.v0.0.1) csv.Spec.Icon elements should contain both data and mediatype`. So I need to add those static fields(+a few more) into the [base manifest](https://github.com/project-codeflare/codeflare-operator/blob/main/config/manifests/bases/codeflare-operator.clusterserviceversion.yaml).

**Comment by tedhtchang** [comment]
/cc @anishasthana I added validate-bundle to the precommit workflow. Please review the changes.
How to test:
- Checkout this PR and run `make bundle` and inspect files in the files bundle/manifests folder.
  - `base64data` and `mediatype` are populated (to pass the additional validators `--select-optional suite=operatorframework` flag).
  - displayName: InstaScale should be w/o space.
  - static fields: annotions.container.(Image, reposiotry, support, operatorframework.io/suggested-namespace),links are populated in the generated csv.
- Build bundle img locally `podman build -f bundle.Dockerfile -t ttl.sh/testmybundle:10m .`
- Push temporary bundle image `podman push ttl.sh/testmybundle:10m`
- Install bundle to your OCP `operator-sdk run bundle ttl.sh/testmybundle:10m` and verify the installed operator from OCP console.
- Remove bundle `operator-sdk cleanup codeflare-operator`

**Review by anishasthana — APPROVED** [review]
/lgtm

**Pull request merged**
