### PR TITLE
Update AppWrappers to v0.22.0

### PR DESCRIPTION
**Pull request by dgrove-oss**
Highlights:
   + Annotations to mark exit codes as being terminal
   + Autopilot: auto-injection of Node anti-affinities
   + Autopilot: Automatic reset/resume of AppWrappers using unhealthy resources
   + Emit an event when an unhealthy appwrapper is being reset

Full Changelog:
   https://github.com/project-codeflare/appwrapper/compare/v0.21.1...v0.22.0

### CODE REVIEW

**Comment by dgrove-oss** [comment]
Will dig into the e2e test failure next week;  out of time for today.

**Comment by dgrove-oss** [comment]
Realized I forgot to carry over the RBAC augmentation to watch Nodes.   Fixed & force pushed.

**Comment by dgrove-oss** [comment]
rebased.

**Review by Bobbins228 — COMMENTED** [review]
/lgtm

**Pull request merged**
