### PR TITLE
Create a Ray Cluster SDK upgrade scenarios during OLM upgrade

### PR DESCRIPTION
**Pull request by Srihari1192**
# Issue link

https://github.com/project-codeflare/codeflare-operator/issues/184
# What changes have been made

 - Added Ray Cluster SDK upgrade scenarios tests **TestMNISTRayClusterUp** and **TestMnistJobSubmit** in upgrade package to run the test before an operator upgrade and after upgrade 
- Adjusted the workflows olm_tests.yaml to include Raycluster upgrade scenarios tests
# Verification steps

## Checks
- [ ] I've made sure the tests are passing. 
- Testing Strategy
   - [ ] Unit tests
   - [ ] Manual tests
   - [ ] Testing is not required for this change

### CODE REVIEW

**Comment by sutaakar** [comment]
@Srihari1192 Could you move this code into [SDK repo](https://github.com/project-codeflare/codeflare-sdk/tree/main/tests)? So that all SDK related tests are on one place.

**Comment by Srihari1192** [comment]
> @Srihari1192 Could you move this code into [SDK repo](https://github.com/project-codeflare/codeflare-sdk/tree/main/tests)? So that all SDK related tests are on one place.

Sure will move this to sdk repo

**Comment by Srihari1192** [comment]
Closing this PR as moving these tests into codeflare-sdk https://github.com/project-codeflare/codeflare-sdk/pull/440

**Pull request closed without merging**
