### PR TITLE
Use dedicated KinD composite action from CodeFlare common

### PR DESCRIPTION
**Pull request by sutaakar**
# Issue link

https://github.com/project-codeflare/codeflare-common/issues/18

# What changes have been made

Replace own KinD composite action with a reference from CodeFlare common repository.

# Verification steps

Run PR checks.

## Checks
- [ ] I've made sure the tests are passing. 
- Testing Strategy
   - [ ] Unit tests
   - [ ] Manual tests
   - [ ] Testing is not required for this change

### CODE REVIEW

**Review by ChristianZaccaria — APPROVED** [review]
Great work! I like to see this amount of code reduction and following DRY principle. The same will be applied on the codeflare-sdk repo. Thanks! /lgtm /approve

**Comment by astefanutti** [comment]
Great!

**Pull request merged**
